"""Canonical imports shared by the contract and numerical tests."""

# Re-export shim: every name here is imported by tests via ``tests._public``.
from mdescriptor import (  # noqa: F401
    AssetPolicy,
    CancelledError,
    ComputeControl,
    ExecutionOptions,
    ModelLoadError,
    OutputOptions,
    StructureBatch,
    builtin_registry,
)
from mdescriptor.descriptors import (  # noqa: F401
    ACE,
    ACSF,
    C00PSMLFF,
    DPA4,
    DPA4C,
    EAD,
    LMBTR,
    MBTR,
    MTP,
    NEP,
    SNAP,
    SO3,
    SO4,
    SOAP,
    AtomicComposition,
    CoulombMatrix,
    EwaldSumMatrix,
    LBispectrum,
    LodeSphericalExpansion,
    NeighborList,
    SineMatrix,
    SoapPowerSpectrum,
    SoapRadialSpectrum,
    SOAPTurbo,
    SortedDistances,
    SphericalExpansion,
    SphericalExpansionByPair,
    ValleOganov,
)
