#pragma once

#include "mdescriptor/detail/batch.hpp"
#include "mdescriptor/cuda/context.hpp"

#include <cstddef>
#include <cstdint>
#include <vector>

namespace mdescriptor::cuda {

// A device-owned copy of the stable CPU batch layout.  The view is private to
// the CUDA plugin; no CUDA pointer is added to the public StructureBatch or
// the CPU headers.
class DeviceBatch {
public:
    DeviceBatch() = default;
    DeviceBatch(const DeviceBatch&) = delete;
    DeviceBatch& operator=(const DeviceBatch&) = delete;
    ~DeviceBatch() noexcept;

    void upload(
        CudaExecutionContext& context,
        const detail::StructureBatchView& batch);
    // Materialize only the periodic replica batch on the device.  The host
    // computes compact cell/offset metadata, while atom numbers, positions,
    // and the replica-to-source mapping are generated by a CUDA kernel.
    bool expand_nep(
        CudaExecutionContext& context,
        const DeviceBatch& source,
        const detail::StructureBatchView& source_host,
        double cutoff);
    void ensure_positions_soa(CudaExecutionContext& context);
    void clear() noexcept;

    std::int64_t structures() const noexcept { return structures_; }
    std::int64_t atoms() const noexcept { return atoms_; }
    const std::int32_t* numbers() const noexcept { return numbers_; }
    const double* positions() const noexcept { return positions_; }
    const double* positions_soa() const noexcept { return positions_soa_; }
    std::int64_t position_stride() const noexcept {
        return static_cast<std::int64_t>(positions_soa_stride_);
    }
    const double* cells() const noexcept { return cells_; }
    const std::int32_t* pbc() const noexcept { return pbc_; }
    const std::int64_t* offsets() const noexcept { return offsets_; }
    bool expanded() const noexcept { return expanded_; }
    std::int64_t original_atoms() const noexcept { return original_atom_count_; }
    const std::int64_t* expansion_first() const noexcept { return expansion_first_; }
    const std::int64_t* expansion_stride() const noexcept { return expansion_stride_; }
    const std::int32_t* expansion_replicas() const noexcept { return expansion_replicas_; }
    detail::StructureBatchView metadata_view() const noexcept {
        return {
            nullptr, nullptr, host_cells_.data(), host_pbc_.data(), host_offsets_.data(),
            structures_, atoms_,
        };
    }

private:
    template <typename Value>
    static void release(Value*& pointer) noexcept;

    std::int32_t* numbers_ = nullptr;
    double* positions_ = nullptr;
    double* positions_soa_ = nullptr;
    double* cells_ = nullptr;
    std::int32_t* pbc_ = nullptr;
    std::int64_t* offsets_ = nullptr;
    std::int64_t structures_ = 0;
    std::int64_t atoms_ = 0;
    std::size_t numbers_capacity_ = 0;
    std::size_t positions_capacity_ = 0;
    std::size_t positions_soa_capacity_ = 0;
    std::size_t positions_soa_stride_ = 0;
    std::size_t cells_capacity_ = 0;
    std::size_t pbc_capacity_ = 0;
    std::size_t offsets_capacity_ = 0;
    bool expanded_ = false;
    std::int64_t original_atom_count_ = 0;
    std::vector<double> host_cells_;
    std::vector<std::int32_t> host_pbc_;
    std::vector<std::int64_t> host_offsets_;
    std::int64_t* expansion_first_ = nullptr;
    std::int64_t* expansion_stride_ = nullptr;
    std::int32_t* expansion_replicas_ = nullptr;
    std::int32_t* expansion_counts_ = nullptr;
    std::size_t expansion_first_capacity_ = 0;
    std::size_t expansion_stride_capacity_ = 0;
    std::size_t expansion_replicas_capacity_ = 0;
    std::size_t expansion_counts_capacity_ = 0;
};

} // namespace mdescriptor::cuda
