"""Stable MDescriptor contracts and explicit registry functions."""

from .core import (
    CancelledError,
    ClosedDescriptorError,
    ComputeControl,
    Descriptor,
    DescriptorConfigError,
    DescriptorInputError,
    DescriptorLevel,
    DescriptorResult,
    ExecutionOptions,
    MDescriptorError,
    ModelLoadError,
    OutputOptions,
    StructureBatch,
    StructureInput,
)
from .registry import (
    AssetPolicy,
    DescriptorConfiguration,
    DescriptorRegistry,
    DescriptorSpec,
    builtin_registry,
    create_descriptor,
    get_descriptor,
    list_descriptors,
)

__all__ = [
    "AssetPolicy",
    "CancelledError",
    "ClosedDescriptorError",
    "ComputeControl",
    "Descriptor",
    "DescriptorConfigError",
    "DescriptorConfiguration",
    "DescriptorInputError",
    "DescriptorLevel",
    "DescriptorRegistry",
    "DescriptorResult",
    "DescriptorSpec",
    "ExecutionOptions",
    "MDescriptorError",
    "ModelLoadError",
    "OutputOptions",
    "StructureBatch",
    "StructureInput",
    "builtin_registry",
    "create_descriptor",
    "get_descriptor",
    "list_descriptors",
]
