"""Static typing surface for the optional native extension.

The compiled module is generated by nanobind during installation.  Keeping a
small stub next to the source-tree fallback lets the core package be checked
without importing or building the extension first.
"""

from typing import Any

def __getattr__(name: str) -> Any: ...

class CancelledError(Exception):
    """Exception raised by a native kernel when cooperative cancellation wins."""


class ComputeControl:
    """Native progress/cancellation state shared with a single computation."""

    def __init__(self) -> None: ...

    def reset(self, total: int) -> None: ...

    def cancel(self) -> None: ...

    def cancelled(self) -> bool: ...

    def completed(self) -> int: ...

    def total(self) -> int: ...

    def mark_completed(self) -> None: ...


class AceOptions:
    species: list[int]
    max_order: int
    r0: float
    transform_p: float
    transform_a: float
    w_l: float
    max_degree: float
    degree_by_order: list[float]
    angular_weight_by_order: list[float]
    degree_csp: float
    degree_chc: float
    degree_ahc: float
    degree_bhc: float
    r_cut: float
    r_in: float
    p_cut: int
    p_in: int
    constants: bool
    num_threads: int

    def __init__(self) -> None: ...


class AceCalculator:
    feature_count: int
    feature_counts: list[int]
    species: list[int]
    max_angular: int
    max_radial: int

    def __init__(self, options: AceOptions) -> None: ...

    def compute(
        self,
        numbers: Any,
        positions: Any,
        cells: Any,
        pbc: Any,
        offsets: Any,
        control: ComputeControl | None = None,
    ) -> Any: ...

    def close(self) -> None: ...

    def closed(self) -> bool: ...
