"""Static typing surface for the optional native extension.

The compiled module is generated by nanobind during installation.  Keeping a
small stub next to the source-tree fallback lets the core package be checked
without importing or building the extension first.
"""

from typing import Any

def __getattr__(name: str) -> Any: ...

class CancelledError(Exception):
    """Exception raised by a native kernel when cooperative cancellation wins."""


class ComputeControl:
    """Native progress/cancellation state shared with a single computation."""

    def __init__(self) -> None: ...

    def reset(self, total: int) -> None: ...

    def cancel(self) -> None: ...

    def cancelled(self) -> bool: ...

    def completed(self) -> int: ...

    def total(self) -> int: ...

    def mark_completed(self) -> None: ...
