"""Check and render the numerical-baseline inventory.

There are two deliberately different kinds of independent evidence:

``external_static``
    The committed ``expected_output.npz`` (or a named sidecar fixture) was
    generated by an upstream or source-derived oracle.  The default test job
    can use it without optional packages.

``external_runtime``
    A pinned provider is invoked by the separate reference job.  This remains
    a useful smoke check even when its output has also been promoted to a
    committed static sidecar.

The checker is intentionally side-effect free except for ``--write`` updating
the generated documentation page.  It is also imported by the ordinary test
suite, so a new descriptor cannot silently ship without an oracle entry.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import mdescriptor

try:  # ``python scripts/check_numerical_baselines.py`` has ``scripts`` on sys.path.
    from .numerical_baselines import BASELINES, STATIC_GOLDEN_KINDS
except ImportError:  # pragma: no cover - exercised by the direct script entry point
    from numerical_baselines import BASELINES, STATIC_GOLDEN_KINDS

ROOT = Path(__file__).resolve().parents[1]
GOLDEN_ROOT = ROOT / "tests" / "golden"
DOC = ROOT / "docs" / "numerical-baselines.md"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _pin_is_declared(package: str, version: str) -> bool:
    """Return whether a runtime provider is pinned in a project extra."""

    text = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    # ``deepmd-kit[torch]`` is the only provider with an extra in its pin.
    normalized = package.replace("_", "-")
    for candidate in (package, normalized):
        if f"{candidate}=={version}" in text or f"{candidate}[torch]=={version}" in text:
            return True
    return False


def _validate_external_fixture(
    name: str,
    fixture_path: Path,
    parent_manifest: dict[str, object],
    baseline: dict[str, object],
    expected: dict[str, str],
    errors: list[str],
) -> None:
    """Validate a provider-generated static sidecar and its provenance."""

    if not fixture_path.is_file():
        errors.append(f"{name}: external static fixture is missing: {fixture_path}")
        return
    try:
        fixture = json.loads(fixture_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        errors.append(f"{name}: cannot read external static fixture {fixture_path}: {exc}")
        return
    if fixture.get("descriptor") != name:
        errors.append(f"{name}: external fixture descriptor is {fixture.get('descriptor')!r}")

    fixture_output = fixture_path.parent / str(fixture.get("expected_output", ""))
    if not fixture_output.is_file():
        errors.append(f"{name}: external fixture output is missing: {fixture_output}")
    else:
        output_digest = baseline.get("expected_output_sha256")
        if not isinstance(output_digest, str) or len(output_digest) != 64:
            errors.append(f"{name}: static sidecar output hash is missing")
        elif _sha256(fixture_output) != output_digest:
            errors.append(f"{name}: static sidecar output hash does not match the manifest")

    fixture_reference = fixture.get("reference")
    if not isinstance(fixture_reference, dict):
        errors.append(f"{name}: external fixture has no reference object")
        fixture_reference = {}
    if fixture_reference.get("kind") != "external_static":
        errors.append(
            f"{name}: external fixture reference kind is {fixture_reference.get('kind')!r}"
        )
    for field in ("provider", "package", "version"):
        if fixture_reference.get(field) != expected[field]:
            errors.append(
                f"{name}: external fixture reference.{field}={fixture_reference.get(field)!r}, "
                f"expected {expected[field]!r}"
            )

    generator = fixture_reference.get("generator")
    generator_path = ROOT / str(generator) if isinstance(generator, str) else None
    if generator != baseline.get("generator") or generator != "scripts/generate_external_static_goldens.py":
        errors.append(f"{name}: external fixture generator is not the approved generator")
    if generator_path is None or not generator_path.is_file():
        errors.append(f"{name}: external fixture generator is missing: {generator_path}")
    else:
        generator_digest = fixture_reference.get("generator_sha256")
        if generator_digest != baseline.get("generator_sha256"):
            errors.append(f"{name}: external fixture generator hash disagrees with parent manifest")
        if generator_digest != _sha256(generator_path):
            errors.append(f"{name}: external fixture generator hash is stale")

    project_output = parent_manifest.get("expected_output")
    project_path = fixture_path.parent / str(project_output)
    project_digest = baseline.get("project_snapshot_sha256")
    if not project_path.is_file():
        errors.append(f"{name}: retained project snapshot is missing: {project_path}")
    elif not isinstance(project_digest, str) or _sha256(project_path) != project_digest:
        errors.append(f"{name}: retained project snapshot hash does not match the manifest")


def _validate_manifest(name: str, manifest_path: Path, errors: list[str]) -> None:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    expected = BASELINES.get(name)
    if expected is None:
        errors.append(f"{name}: missing entry in scripts/numerical_baselines.py")
        return

    baseline = manifest.get("numeric_baseline")
    if not isinstance(baseline, dict):
        errors.append(f"{name}: manifest has no numeric_baseline object")
        return
    for key, value in expected.items():
        if baseline.get(key) != value:
            errors.append(
                f"{name}: numeric_baseline.{key}={baseline.get(key)!r}, expected {value!r}"
            )

    output_path = manifest_path.parent / manifest.get("expected_output", "")
    if not output_path.is_file():
        errors.append(f"{name}: expected output is missing: {output_path}")
    elif "fixture" not in baseline:
        output_digest = baseline.get("expected_output_sha256")
        if not isinstance(output_digest, str) or len(output_digest) != 64:
            errors.append(f"{name}: numeric_baseline.expected_output_sha256 is missing")
        elif _sha256(output_path) != output_digest:
            errors.append(f"{name}: expected output hash does not match the manifest")

    fixture_name = baseline.get("fixture")
    if fixture_name is not None:
        if not isinstance(fixture_name, str) or Path(fixture_name).name != fixture_name:
            errors.append(f"{name}: numeric_baseline.fixture must be a local filename")
        else:
            _validate_external_fixture(
                name,
                manifest_path.parent / fixture_name,
                manifest,
                baseline,
                expected,
                errors,
            )

    test_path = ROOT / expected["test"]
    if not test_path.is_file():
        errors.append(f"{name}: oracle evidence path is missing: {test_path}")
    elif "marker" in expected:
        source = test_path.read_text(encoding="utf-8")
        marker = expected["marker"]
        if f"pytest.mark.{marker}" not in source and f'"{marker}"' not in source:
            errors.append(f"{name}: oracle test does not declare marker {marker!r}")
        if not _pin_is_declared(expected["package"], expected["version"]):
            errors.append(
                f"{name}: provider {expected['package']}=={expected['version']} is not pinned"
            )

    reference_kind = manifest.get("reference", {}).get("kind")
    if expected["kind"] == "external_static":
        if baseline.get("committed_golden") != "external_static":
            errors.append(f"{name}: static oracle must declare external_static golden")
        if fixture_name is None and reference_kind not in STATIC_GOLDEN_KINDS:
            errors.append(
                f"{name}: static oracle has non-external reference kind {reference_kind!r}"
            )
        if fixture_name is not None and reference_kind != "project_commit":
            errors.append(
                f"{name}: sidecar static oracle must retain project_commit snapshot reference, "
                f"got {reference_kind!r}"
            )
    else:
        if baseline.get("committed_golden") != "project_commit":
            errors.append(f"{name}: runtime oracle must retain project_commit golden provenance")
        if reference_kind != "project_commit":
            errors.append(
                f"{name}: runtime oracle expected project_commit reference, got {reference_kind!r}"
            )


def validate_manifests() -> None:
    """Raise ``AssertionError`` when baseline coverage or provenance drifts."""

    errors: list[str] = []
    manifest_paths = sorted(GOLDEN_ROOT.glob("*/manifest.json"))
    manifest_names: set[str] = set()
    for path in manifest_paths:
        manifest = json.loads(path.read_text(encoding="utf-8"))
        name = manifest.get("descriptor")
        if not isinstance(name, str):
            errors.append(f"{path}: descriptor name is missing")
            continue
        manifest_names.add(name)
        _validate_manifest(name, path, errors)

    registry_names = set(mdescriptor.list_descriptors())
    baseline_names = set(BASELINES)
    if baseline_names != registry_names:
        errors.append(
            "baseline inventory and descriptor registry differ: "
            f"missing={sorted(registry_names - baseline_names)!r}, "
            f"extra={sorted(baseline_names - registry_names)!r}"
        )
    if manifest_names != baseline_names:
        errors.append(
            "baseline inventory and golden manifests differ: "
            f"missing={sorted(baseline_names - manifest_names)!r}, "
            f"extra={sorted(manifest_names - baseline_names)!r}"
        )
    if len(manifest_paths) != len(BASELINES):
        errors.append(f"expected {len(BASELINES)} golden manifests, found {len(manifest_paths)}")

    if errors:
        raise AssertionError("numerical baseline inventory is invalid:\n- " + "\n- ".join(errors))


def render() -> str:
    """Render the checked-in human-readable baseline table."""

    rows: list[str] = []
    for name in mdescriptor.list_descriptors():
        baseline = BASELINES[name]
        committed = "external static" if baseline["kind"] == "external_static" else "project snapshot"
        runtime = f"`{baseline['marker']}`" if "marker" in baseline else "—"
        rows.append(
            f"| `{name}` | {committed} | {baseline['provider']} | "
            f"`{baseline['package']}` ({baseline['version']}) | {runtime} |"
        )
    return (
        "# Numerical baselines / 数值基线\n\n"
        "The repository has a committed numerical golden for every descriptor.\n"
        "An `external_static` entry means the values came from an independent\n"
        "upstream/source oracle.  The 21 provider-backed entries keep the older\n"
        "project snapshot as a secondary contract fixture and add an\n"
        "`external_manifest.json` sidecar as the primary numerical oracle.\n"
        "The pinned provider tests remain a separate runtime smoke check.\n\n"
        "当前 28 个描述符全部有外部静态数值 golden：7 个沿用已提交的\n"
        "source-derived NPZ，另外 21 个由锁定版本的独立 provider 生成\n"
        "sidecar。21 个旧 project snapshot 仍保留，用于覆盖原有布局、\n"
        "metadata 与非周期契约；它们不再被冒充为 upstream 数值来源。\n\n"
        "| Descriptor | Committed golden | Independent oracle | Package/source | CI marker |\n"
        "|---|---|---|---|---|\n"
        + "\n".join(rows)
        + "\n\n"
        "The NPZ comparisons check values and all result identity fields\n"
        "(`samples`, labels, level, structure ids and row offsets).  Contract,\n"
        "periodicity, symmetry and lifecycle tests remain separate because a\n"
        "numeric golden cannot prove those behaviours.\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="validate manifests and generated docs")
    mode.add_argument("--write", action="store_true", help="validate manifests and write docs")
    args = parser.parse_args(argv)

    validate_manifests()
    expected = render()
    if args.write:
        DOC.write_text(expected, encoding="utf-8")
        return 0
    actual = DOC.read_text(encoding="utf-8")
    if actual != expected:
        raise SystemExit("numerical baseline documentation is stale; run with --write")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
